# Generated by Django 3.0 on 2020-04-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
                ('player_dob', models.DateTimeField(verbose_name='Date Of Birth')),
                ('player_class', models.CharField(choices=[('K', 'Knight'), ('W', 'Warlord'), ('S', 'Sorcerer'), ('R', 'Rogue')], default='K', max_length=1)),
                ('player_power', models.PositiveIntegerField()),
                ('player_description', models.TextField()),
            ],
        ),
    ]
